# Generated by Django 2.1.1 on 2018-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankco2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='user',
        ),
        migrations.AddField(
            model_name='step',
            name='device_id',
            field=models.CharField(default='default-id', max_length=255),
        ),
    ]
