# Generated by Django 2.1.1 on 2018-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankco2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='character_code',
            field=models.CharField(default='code', max_length=32),
        ),
    ]
