# Generated by Django 2.1.1 on 2018-09-01 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('account', '0002_email_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('bankco2', '0002_step_character_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankco2user',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='step',
            name='character_code',
        ),
        migrations.AddField(
            model_name='step',
            name='device_id',
            field=models.CharField(default='-1', max_length=512),
        ),
        migrations.AlterField(
            model_name='step',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BankCo2User',
        ),
    ]
