# Generated by Django 2.1.1 on 2018-09-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankco2', '0003_auto_20180902_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bankco2.Device'),
            preserve_default=False,
        ),
    ]
