# Generated by Django 2.1.1 on 2018-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankco2', '0004_step_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
