# Generated by Django 2.1.1 on 2018-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankco2', '0006_auto_20180902_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='draw_flag',
            field=models.BooleanField(default=False),
        ),
    ]
